AstroJournalClub/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register', views.register_request, name='register'),
    path('login', views.login_request, name='login'),
    path('logout', views.logout_request, name='logout'),
]

AstroJournalClub/main/urls.py
from django.urls import path
from . import views


app_name = "main"


urlpatterns = [
    path('', views.home, name='home'),
    path('meeting/', views.meeting, name='meeting'),
    path('publications/', views.publications, name='publications'),
    path('publications/<int:year>-<int:month>-<int:day>/', views.publications, name='publications'),
    path('api/<int:year>-<int:month>-<int:day>/<str:identifier>/vote', views.vote, name='vote'),
    path('api/<int:year>-<int:month>-<int:day>/<str:identifier>/present', views.present, name='present')
]

AstroJournalClub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('AstroJournalClub.main.urls')),
    path('accounts/', include('AstroJournalClub.accounts.urls')),
    path('admin/', admin.site.urls),
]

AstroJournalClub/main/models.py
import datetime
from typing import List

from django.contrib.auth.models import User
from django.db import models

# Create your models here.


class Category(models.Model):
    """Category for publications."""

    name = models.CharField('Category name', max_length=20, db_index=True)

    def __str__(self):
        return self.name


class Author(models.Model):
    """Author of a publication."""

    name = models.CharField('Name of author', max_length=100, db_index=True)
    url = models.CharField('arXiv URL', max_length=100)

    def __str__(self):
        return '<a href="%s">%s</a' % (self.url, self.name)


class Publication(models.Model):
    """A publication in arxiv."""

    identifier = models.CharField('arXiv identifier', max_length=15, db_index=True)
    date = models.DateField('Date of submission.', db_index=True)
    number = models.IntegerField('arXiv post number on day')
    title = models.CharField('Title of publication', max_length=200)
    url = models.CharField('arXiv URL', max_length=100)
    summary = models.TextField('Summary')
    categories = models.ManyToManyField(Category)

    def to_dict(self, user: User):
        # basic data
        data = {
            'identifier': self.identifier,
            'date': self.date.strftime('%Y-%m-%d'),
            'number': self.number,
            'title': self.title,
            'url': self.url,
            'summary': self.summary,
            'categories': [str(cat) for cat in self.categories.all()],
            'authors': [str(author) for author in self.authors]
        }

        # private stuff
        if user.is_authenticated:
            # get extra fields
            for k, v in self.extras(user).items():
                data[k] = v

        # finished
        return data

    def extras(self, user: User):
        return {
            'votes': self.vote_set.count(),
            'has_voted': any([user == v.user for v in self.vote_set.all()]),
            'wants_present': any([user == v.user and v.present for v in self.vote_set.all()]),
            'presenters': [v.user.username for v in self.vote_set.all() if v.present]
        }

    @property
    def authors(self) -> List[Author]:
        """Return list of authors in order."""

        return [pa.author for pa in PublicationAuthor.objects.filter(publication=self).order_by('order')]

    def add_author(self, order: int, author: Author):
        """Add a new author to this publication.

        Args:
            order: Order of new author in this publication.
            author: Author to add.
        """

        # get or create connection
        PublicationAuthor.objects.get_or_create(publication=self, order=order, author=author)


class PublicationAuthor(models.Model):
    """Authors for a publication."""

    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, db_index=True)
    order = models.IntegerField('Order of authors in this publication.')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, db_index=True)

    class Meta:
        db_table = "main_publication_authors"


class Schedule(models.Model):
    """A schedule for the meetings."""

    start = models.DateField('First day of schedule.')
    end = models.DateField('Last day of schedule.', default='2100-12-31')
    time = models.TimeField('Starting time of meeting.')
    duration = models.FloatField('Duration of meeting in hours.')
    frequency = models.CharField('Frequency of schedule in iCal notation.', max_length=50)

    def __str__(self):
        # basic string (weekday at time)
        s = self.start.strftime('%A') + ' at ' + self.time.strftime('%H:%M')

        # finished?
        if self.end < datetime.date.today():
            s += ' (finished)'
        elif self.start > datetime.date.today():
            s += ' (starts on %s)' % self.start.strftime('%y-%m-%d')

        # finished
        return s

    def next_meeting_time(self):
        """Returns time of next meeting."""

        # check now against end of schedule
        now = datetime.datetime.utcnow()
        if datetime.datetime.combine(self.end, self.time) < now:
            return None

        # get date and time of first meeting
        dt = datetime.datetime.combine(self.start, self.time)

        # go forward until we're in the future
        while dt < now:
            if self.frequency.lower() == 'weekly':
                dt += datetime.timedelta(weeks=1)
            else:
                # unknown frequency format
                return None

        # found date
        return dt

    @staticmethod
    def all_next_meeting_time():
        """Returns the next meeting time for all schedules in database."""

        # get next times from all schedules
        next_times = list(filter(
            lambda x: x[0] is not None, [(s.next_meeting_time(), s) for s in Schedule.objects.all()]
        ))

        # got any?
        return None if len(next_times) == 0 else min([t for t in next_times])


class Vote(models.Model):
    """A vote for a publication."""

    publication = models.ForeignKey(Publication, on_delete=models.CASCADE, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, db_index=True)
    time = models.DateTimeField('Time of vote.', auto_now_add=True)
    present = models.BooleanField('Whether user wants to present paper.', default=False)

AstroJournalClub/main/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.http import JsonResponse, Http404
from django.shortcuts import redirect, render
import json
import datetime
from django.urls import reverse

from AstroJournalClub.main.models import Publication, Vote, Schedule


def home(request):
    response = redirect(reverse('main:publications'))
    return response


def publications(request, year=None, month=None, day=None):
    # build date
    if year is None or month is None or day is None:
        date = datetime.date.today()
    else:
        date = datetime.date(year=year, month=month, day=day)

    # get data
    data = [pub.to_dict(request.user) for pub in Publication.objects.filter(date=date)]

    # render page
    return render(request, 'main/publications.html', context={'date': date,
                                                              'publications': json.dumps(data)})


@login_required
def vote(request, year, month, day, identifier):
    # build date
    date = datetime.datetime(year=year, month=month, day=day)

    # get publication
    pub = Publication.objects.get(date=date, identifier=identifier)

    # vote up or down?
    if any([request.user == v.user for v in pub.vote_set.all()]):
        Vote.objects.filter(publication=pub, user=request.user).delete()
    else:
        Vote.objects.get_or_create(publication=pub, user=request.user)

    # return number of votes and has_voted
    return JsonResponse(pub.extras(request.user))


@login_required
def present(request, year, month, day, identifier):
    # build date
    date = datetime.datetime(year=year, month=month, day=day)

    # get publication
    pub = Publication.objects.get(date=date, identifier=identifier)

    # vote must exist
    try:
        vote = Vote.objects.get(publication=pub, user=request.user)
    except Vote.DoesNotExist:
        raise Http404

    # present or not?
    vote.present = not vote.present
    vote.save()

    # return number of votes and has_voted
    return JsonResponse(pub.extras(request.user))


def meeting(request):
    # get start date of range
    start = datetime.datetime.utcnow() - datetime.timedelta(days=14)

    # get publications with votes on that meeting
    pubs = Publication.objects\
        .annotate(vote_count=Count('vote'))\
        .filter(vote_count__gt=0, vote__time__gt=start)

    # get publications and date of next meeting
    pubs = [pub.to_dict(request.user) for pub in pubs]
    time, _ = Schedule.all_next_meeting_time()

    # render page
    return render(request, 'main/meeting.html', context={'date': time, 'publications': json.dumps(pubs)})

AstroJournalClub/main/templates/main/base.html
<!doctype html>
{% load static version %}
<html>
<head>
    <title>AstroJournalClub</title>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" href="{% static "css/bootstrap-datepicker.min.css" %}">
    <script src="{% static "js/jquery-3.5.1.min.js" %}"></script>
    <script src="{% static "js/vue.js" %}"></script>
    <script src="{% static "js/vue-resource.js" %}"></script>
    <script src="{% static "js/bootstrap-datepicker.min.js" %}"></script>
</head>
<body>

{% include "main/nav.html" %}

<div id="main" class="container">
    <div id="alert-error"></div>
    {% block content %}
    {% endblock %}
</div>

<footer class="bg-danger">
    AstroJournalClub v{% version %}
    (<a href="https://github.com/thusser/AstroJournalClub">GitHub</a>)
    by <a href="mailto:thusser@uni-goettingen.de">Tim-Oliver Husser</a>
</footer>
</body>
</html>

AstroJournalClub/main/templates/main/meeting.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}

    {% if date is None %}

        <h3>No meeting found</h3>

    {% else %}

        <h3>Journal club on {{ date|date:"Y-m-d" }} at {{ date|date:"H:i" }}</h3>
        <hr class="my-4">

        {% include "main/publication_list.html" %}


    {% endif %}

{% endblock %}

AstroJournalClub/main/templates/main/nav.html
<nav class="navbar navbar-expand-lg bg-danger">
    <a class="navbar-brand" href="{% url 'main:home' %}">AJC</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.resolver_match.url_name == "publications" %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:publications' %}">
                    Publications
                    {% if request.resolver_match.url_name == "publications" %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == "meeting" %}active{% endif %}">
                <a class="nav-link" href="{% url 'main:meeting' %}">
                    Next meeting
                    {% if request.resolver_match.url_name == "meeting" %}
                        <span class="sr-only">(current)</span>
                    {% endif %}
                </a>
            </li>
        </ul>

        <ul class="navbar-nav">
            {% if user.is_authenticated %}

                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                <li class="nav-item"><a class="nav-link" href="#">Welcome, {{ user.username }}</a></li>

            {% else %}

                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>

            {% endif %}
        </ul>
    </div>
</nav>

AstroJournalClub/main/templates/main/publication_list.html
{% load static %}

<div id="app" v-cloak>

    <h4>Filters</h4>
    <form>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph" value="astro-ph"
                   v-model="categoryFilter" @change="toggleAstroPhFilter()">
            <label class="form-check-label" for="filter-astro-ph">ASTRO-PH</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-co" value="astro-ph.CO"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-co">CO</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-ep" value="astro-ph.EP"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-ep">EP</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-ga" value="astro-ph.GA"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-ga">GA</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-he" value="astro-ph.HE"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-he">HE</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-im" value="astro-ph.IM"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-im">IM</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-astro-ph-sr" value="astro-ph.SR"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-astro-ph-sr">SR</label>
        </div>
    </form>
    <form>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-gr-qc" value="gr-qc"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-gr-qc">GR-QC</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-hep-ph" value="hep-ph"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-hep-ph">HEP-PH</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-hep-th" value="hep-th"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-hep-th">HEP-TH</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-hep-lat" value="hep-lat"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-hep-lat">HEP-LAT</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-hep-ex" value="hep-ex"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-hep-ex">HEP-EX</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-nucl-th" value="nucl-th"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-nucl-th">NUCL-TH</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="checkbox" id="filter-nucl-ex" value="nucl-ex"
                   v-model="categoryFilter">
            <label class="form-check-label" for="filter-nucl-ex">NUCL-EX</label>
        </div>
    </form>

    <div class="card" v-for="pub in filteredPublications" v-bind:key="pub.identifier">
        <div class="card-body">

            <div class="card-header">
                <h5>[astro-ph #[[ pub.number ]]] [[ pub.title ]]</h5>
            </div>

            <div class="row card-text">

                <div class="col-3">
                    {% if user.is_authenticated %}
                        <div class="row">
                            <div class="col-8 text-center">
                                <p><span class="votes">[[ pub.votes ]]</span><br>votes</p>
                            </div>
                            <div class="col-4">
                                <button v-if="!pub.has_voted" class="button btn-sm btn-success"
                                        v-on:click="vote(pub, +1)">
                                    <img src="{% static 'images/thumbs-up-solid.svg' %}"
                                         alt="Vote up" width="16" height="16">
                                </button>
                                <button v-if="pub.has_voted" class="button btn-sm btn-danger"
                                        v-on:click="vote(pub, -1)">
                                    <img src="{% static 'images/thumbs-down-solid.svg' %}"
                                         alt="Vote down" width="16" height="16">
                                </button>
                                <br />
                                <button v-if="!pub.wants_present & pub.has_voted" class="button btn-sm btn-success"
                                        v-on:click="present(pub, +1)">
                                    <img src="{% static 'images/volume-up-solid.svg' %}"
                                         alt="Want to present" width="16" height="16">
                                </button>
                                <button v-if="pub.wants_present" class="button btn-sm btn-danger"
                                        v-on:click="present(pub, -1)">
                                    <img src="{% static 'images/volume-mute-solid.svg' %}"
                                         alt="Do not want to present" width="16" height="16">
                                </button>
                            </div>
                        </div>
                        <p class="presenters" v-if="pub.presenters.length > 0">
                            <strong>Presenters:</strong><br />
                            [[ pub.presenters.join(', ') ]]
                        </p>
                    {% else %}
                        <p>
                            <a href="{% url 'accounts:login' %}">Login</a> to vote.
                        </p>
                    {% endif %}
                </div>
                <div class="col-8">
                    <p>
                        <span v-for="(author, index) in pub.authors">
                            <span v-html="author"></span><span v-if="index+1 < pub.authors.length">, </span>
                        </span>
                    </p>
                    <p>
                        ArXiV #:
                        <a v-bind:href="'http://arxiv.org/abs/' + pub.identifier">
                            [[ pub.identifier ]]
                        </a>
                        (<a v-bind:href="'http://arxiv.org/pdf/' + pub.identifier">PDF</a>,
                        <a v-bind:href="'http://arxiv.org/ps/' + pub.identifier">PS</a>,
                        <a v-bind:href="'http://adsabs.harvard.edu/cgi-bin/bib_query?' + pub.identifier">ADS</a>)
                    </p>

                    <p><small>Originally posted [[ pub.date ]]</small></p>
                </div>

                <div class="col-1 pub-main">
                    <span v-for="cat in pub.categories">
                        [[ cat.replace('astro-ph.', '') ]]
                    </span>
                </div>

            </div>

            <p v-html="pub.summary"></p>
        </div>
    </div>
</div>

<script>
    let publications = {{ publications|safe }};
</script>
<script src="{% static 'js/publication_list.js' %}"></script>

AstroJournalClub/main/templates/main/publications.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}


    <h3>Publications on {{ date|date:"Y-m-d" }}</h3>
    <hr class="my-4">


    <div class="row">
        <div class="col-9">
            {% include "main/publication_list.html" %}
        </div>
        <div class="col-3">
            <div id="datepicker" data-date-format='yyyy-mm-dd' data-date="{{ date|date:"Y/m/d" }}"
                 data-date-today-highlight="true"></div>
        </div>
    </div>

    <script>
        calendar = $('#datepicker').datepicker()
            .on('changeDate', (event) => {
                $(location).attr('href', '/publications/' + event.format('yyyy-mm-dd') + '/');
            });
    </script>

{% endblock %}